from __future__ import annotations

from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).resolve().parents[2]
BASE_DIR = PROJECT_ROOT
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
RESULTS_DIR = PROJECT_ROOT / "results"
TABLE_DIR = RESULTS_DIR / "tables"
FIGURE_DIR = RESULTS_DIR / "figures"
AUDIO_OUTPUT_DIR = RESULTS_DIR / "audio"
MODEL_DIR = PROJECT_ROOT / "models"

DEMO_ZIP_CANDIDATES = [
    DATA_DIR / "声波文件.zip",
    DATA_DIR / "声波文件(1).zip",
]
DEMO_DATA_DIR = RAW_DATA_DIR
DEMO_OUTPUT_DIR = RESULTS_DIR

DEMO_PULSE_CSV = TABLE_DIR / "acoustic_pulses.csv"
DEMO_RECORDING_CSV = TABLE_DIR / "recording_detection_summary.csv"
CLUSTERED_PULSE_CSV = TABLE_DIR / "acoustic_clusters_ABCD.csv"
RECORDING_CLUSTER_CSV = TABLE_DIR / "recording_cluster_summary.csv"
CLUSTER_CENTER_CSV = TABLE_DIR / "cluster_centers_ABCD.csv"
CLUSTER_REPRESENTATIVE_CSV = TABLE_DIR / "cluster_representatives.csv"
CLUSTER_PCA_PNG = FIGURE_DIR / "cluster_pca_ABCD.png"
CLUSTER_MODEL_PATH = MODEL_DIR / "acoustic_type_ABCD_model.joblib"
CLUSTER_METADATA_JSON = MODEL_DIR / "acoustic_type_ABCD_metadata.json"
CLUSTER_EXAMPLE_DIR = FIGURE_DIR / "cluster_examples"
DEMO_PREDICTION_DIR = RESULTS_DIR / "predictions"
SPECTROGRAM_DIR = FIGURE_DIR / "spectrograms"
PULSE_ZOOM_DIR = FIGURE_DIR / "pulse_zooms"
CUT_PULSE_DIR = AUDIO_OUTPUT_DIR / "cut_pulses"
REJECTED_PULSE_DIR = AUDIO_OUTPUT_DIR / "rejected_pulses"
SEPARATED_PULSE_DIR = AUDIO_OUTPUT_DIR / "separated_pulses"
NOISE_GATE_MODEL_PATH = MODEL_DIR / "noise_bat_gate_model.joblib"
COMBINED_DEMO_MODEL_PATH = MODEL_DIR / "noise_bat_ABCD_model.joblib"
NOISE_GATE_PREDICTIONS_CSV = TABLE_DIR / "noise_gate_validation.csv"

TARGET_SAMPLE_RATE = 250_000

LOW_FREQ_HZ = 15_000

HIGH_FREQ_HZ = 120_000

ENERGY_THRESHOLD_DB = -28.0       # 相对最强能量的阈值

MIN_PULSE_MS = 0.8

MAX_PULSE_MS = 40.0

MERGE_GAP_MS = 1.5

PULSE_PADDING_MS = 0.4

CORE_THRESHOLD_DB = -24.0

CORE_BACKGROUND_MARGIN_DB = 6.0

CORE_MAX_THRESHOLD_DB = -10.0

CORE_CONTEXT_MS = 2.0

CORE_PADDING_MS = 0.20

CORE_MAX_GAP_MS = 0.35

MIN_PULSE_SNR_DB = 4.0

MIN_TRACK_COVERAGE = 0.55

MAX_TRACK_JUMP_KHZ = 35.0

TOP_PULSES_PER_FILE = 10

ZOOM_CONTEXT_MS = 3.0

CONTOUR_MIN_DB = -35.0

RANDOM_STATE = 42

CLUSTER_FEATURE_COLUMNS = [
    "duration_ms",
    "peak_freq_khz",
    "start_freq_khz",
    "end_freq_khz",
    "frequency_drop_khz",
    "f05_khz",
    "f95_khz",
    "bandwidth_90_khz",
    "slope_khz_per_ms",
    "track_coverage",
    "max_track_jump_khz",
]

N_ACOUSTIC_TYPES = 4

MAX_CLUSTER_PULSES_PER_RECORDING = 150

REPRESENTATIVE_PULSES_PER_TYPE = 10

MIN_PULSES_FOR_CLUSTERING = 40

ACOUSTIC_TYPE_DESCRIPTIONS = {
    "A": "短促宽带下降FM型",
    "B": "高频窄带或CF型",
    "C": "低频窄带或缓变型",
    "D": "复杂、中间或混合声型",
}

DETECTION_CHUNK_SECONDS = 4.0

DETECTION_CHUNK_OVERLAP_MS = 50.0

MAX_ANALYSIS_WINDOWS_PER_RECORDING = 2

SAVE_PER_RECORDING_DIAGNOSTICS = False

DEMO_DETECTION_HOP_LENGTH = 256

OVERVIEW_MAX_TIME_BINS = 4000

MAX_REFINED_PULSES_PER_RECORDING = 350

ENABLE_SIMULTANEOUS_SEPARATION = True

SEPARATION_N_FFT = 1024

SEPARATION_WIN_LENGTH = 256

SEPARATION_HOP_LENGTH = 32

SEPARATION_MAX_COMPONENTS = 3

SEPARATION_MAX_PEAKS_PER_FRAME = 5

SEPARATION_MIN_FREQ_GAP_KHZ = 1.5

SEPARATION_PEAK_PROMINENCE_DB = 2.5

SEPARATION_FRAME_DYNAMIC_RANGE_DB = 22.0

SEPARATION_GLOBAL_MIN_DB = -38.0

SEPARATION_MAX_TRACK_JUMP_KHZ = 5.0

SEPARATION_MAX_TRACK_GAP_FRAMES = 2

SEPARATION_MIN_TRACK_MS = 0.55

SEPARATION_MIN_TRACK_COVERAGE = 0.50

SEPARATION_MIN_TEMPORAL_OVERLAP = 0.45

SEPARATION_MIN_SECONDARY_RELATIVE_DB = -18.0

SEPARATION_MASK_BANDWIDTH_KHZ = 1.2

SEPARATION_HARMONIC_TOLERANCE = 0.06

SAVE_SEPARATED_PULSE_AUDIO = True

NOISE_GATE_FEATURE_COLUMNS = [
    "duration_ms",
    "peak_freq_khz",
    "start_freq_khz",
    "end_freq_khz",
    "frequency_drop_khz",
    "f05_khz",
    "f95_khz",
    "bandwidth_90_khz",
    "slope_khz_per_ms",
    "snr_db",
    "track_coverage",
    "max_track_jump_khz",
]

MAX_NOISE_GATE_ROWS_PER_SOURCE_CLASS = 120

MIN_NOISE_GATE_ROWS_PER_CLASS = 20

NOISE_BAT_PROBABILITY_THRESHOLD = 0.55
